# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('todo_task_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('todo_task', models.TextField()),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Medium')], default='M', max_length=1)),
            ],
        ),
    ]
